"""empty message

Revision ID: 3d6589053b35
Revises: 969c07e19e29
Create Date: 2018-06-14 11:04:32.951094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6589053b35'
down_revision = '969c07e19e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('notificationId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('notifyTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.userId'], ),
    sa.PrimaryKeyConstraint('notificationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notification')
    # ### end Alembic commands ###
