"""empty message

Revision ID: c7c299e44c97
Revises: 3d6589053b35
Create Date: 2018-06-15 18:04:56.075437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c299e44c97'
down_revision = '3d6589053b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tag', sa.Column('parentId', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'Tag', 'Tag', ['parentId'], ['tagId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tag', type_='foreignkey')
    op.drop_column('Tag', 'parentId')
    # ### end Alembic commands ###
